language: php

sudo: false

php:
    - 7.0
    - hhvm

matrix:
    fast_finish: true

before_install:
    - phpenv config-rm xdebug.ini || true
    - composer self-update

install:
    - composer install -o

script:
    - make tests
